### PR TITLE
now we can get upvalue name + build with for LUABIND_NO_EXCEPTIONS mode

### PR DESCRIPTION
**Pull request by bagobor**
Sorry for second fix in single pull request. (It was automatically added as I pushed new fix to my fork.)

### CODE REVIEW

**Comment by nitrocaster** [comment]
Why don't you provide a test for this feature?

**Comment by bagobor** [comment]
Sample code for upvalue name ( I used it to avoid chunk recompilation in my scripted entity system):
```c++
	luaL_loadstring(L,script.c_str());
	luabind::object compiledScript(luabind::from_stack(L, -1));

	for (int index = 1;;++index) { 
		auto upv = luabind::getupvalue(compiledScript, index);
		auto name = std::get<0>(upv);
		if (!name) break;
		std::cout << name << endl;
	}
```

**Comment by nitrocaster** [comment]
Looks reasonable for me. @decimad, how about merge?

**Comment by decimad** [comment]
There we go! Thank you!

**Pull request merged**
